import * as THREE from "three";
import gsap from "gsap";
import "./styles.css";

const CONFIG={recipient:"Jia",sender:"Ming",passcodeHash:"207fd47ed6a8671043e9f79626bb8826c1d306f0ca5ac300e10d53094fe206d0"};
const copy={
en:{privateFor:`MADE ESPECIALLY FOR ${CONFIG.recipient.toUpperCase()}`,lockTitle:"This surprise belongs to someone special.",lockBody:"Enter the four numbers that mean something to both of you.",hintLabel:"Hint:",hintText:"The day our story began",unlock:"Unlock the surprise",wrong:"Almost. Think of a day that belongs to us.",heroKicker:"A LITTLE MOMENT, MADE FROM US",heroTitle:"I made a little surprise for you.",heroBody:"Take a breath. Turn up the sound. Let the moment unfold.",enter:"Enter our story",selectKicker:"CHOOSE A MOMENT",selectTitle:"Choose the shape of your surprise.",forLove:"For Love",forBirthday:"For a Birthday",forDate:"For a Date",ready:"Ready",comingNext:"Coming next",chooseHint:"Choose the heart to continue.",releaseKicker:"OUR MEMORIES, HELD TOGETHER",releaseTitle:"Every light holds a piece of us.",releaseBody:"Move gently. When you are ready, set the memories free.",release:"Release the memories",memoryKicker:"SIX LITTLE MOMENTS",memoryTitle:"Every piece of this leads back to you.",memoryHint:"Tap a memory to bring it closer.",finaleButton:"Discover the final message →",finaleKicker:"THE FINAL REVEAL",finaleTitle:"Same sky. Different days. Always us.",finaleBody:"Thank you for making ordinary moments feel unforgettable.",replay:"Replay the moment"},
bm:{privateFor:`DIBUAT KHAS UNTUK ${CONFIG.recipient.toUpperCase()}`,lockTitle:"Kejutan ini milik seseorang yang istimewa.",lockBody:"Masukkan empat nombor yang bermakna untuk kamu berdua.",hintLabel:"Petunjuk:",hintText:"Hari kisah kita bermula",unlock:"Buka kejutan ini",wrong:"Hampir. Fikirkan hari yang menjadi milik kita.",heroKicker:"SATU DETIK KECIL, TERCIPTA DARIPADA KITA",heroTitle:"Saya sediakan satu kejutan kecil untuk awak.",heroBody:"Tarik nafas. Naikkan bunyi. Biarkan detik ini bermula.",enter:"Masuk ke kisah kita",selectKicker:"PILIH SATU DETIK",selectTitle:"Pilih bentuk kejutan anda.",forLove:"Untuk Cinta",forBirthday:"Untuk Hari Jadi",forDate:"Untuk Temu Janji",ready:"Sedia",comingNext:"Akan datang",chooseHint:"Pilih hati untuk meneruskan.",releaseKicker:"KENANGAN KITA, DISATUKAN",releaseTitle:"Setiap cahaya menyimpan sebahagian daripada kita.",releaseBody:"Gerak perlahan. Apabila bersedia, lepaskan kenangan ini.",release:"Lepaskan kenangan",memoryKicker:"ENAM DETIK KECIL",memoryTitle:"Setiap cebisan ini membawa saya kembali kepada awak.",memoryHint:"Sentuh kenangan untuk melihatnya dengan lebih dekat.",finaleButton:"Temui mesej terakhir →",finaleKicker:"PENDEDAHAN TERAKHIR",finaleTitle:"Langit yang sama. Hari yang berbeza. Tetap kita.",finaleBody:"Terima kasih kerana menjadikan detik biasa begitu bermakna.",replay:"Main semula"},
zh:{privateFor:`为 ${CONFIG.recipient.toUpperCase()} 特别准备`,lockTitle:"这份惊喜，只属于一个特别的人。",lockBody:"输入对你们两人有意义的四个数字。",hintLabel:"提示：",hintText:"我们的故事开始的那一天",unlock:"打开这份惊喜",wrong:"差一点。想想那个只属于我们的日子。",heroKicker:"一个由我们组成的小小瞬间",heroTitle:"我为你准备了一份小惊喜。",heroBody:"深呼吸，打开声音，让这一刻慢慢展开。",enter:"进入我们的故事",selectKicker:"选择一个瞬间",selectTitle:"选择你的惊喜形状。",forLove:"为爱",forBirthday:"生日惊喜",forDate:"约会邀请",ready:"已准备",comingNext:"即将推出",chooseHint:"选择爱心继续。",releaseKicker:"我们的回忆，紧紧相连",releaseTitle:"每一道光，都藏着我们的片段。",releaseBody:"轻轻移动。准备好后，让回忆绽放。",release:"释放回忆",memoryKicker:"六个小小瞬间",memoryTitle:"所有碎片，最终都带我回到你身边。",memoryHint:"点击一段回忆，让它靠近你。",finaleButton:"揭晓最后的信息 →",finaleKicker:"最后的惊喜",finaleTitle:"同一片天空，不同的日子，永远是我们。",finaleBody:"谢谢你，让平凡的时刻变得难以忘怀。",replay:"重温这一刻"}
};

const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const canvas=document.querySelector("#particle-canvas");
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:false,powerPreference:"high-performance"});
renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.65));renderer.setSize(innerWidth,innerHeight);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x070a10,.055);
const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,100);camera.position.set(0,0,12);

const count=innerWidth<720?2200:4800,positions=new Float32Array(count*3),targets=new Float32Array(count*3),dispersed=new Float32Array(count*3),particleColors=new Float32Array(count*3),rose=new THREE.Color(0xa94f55),gold=new THREE.Color(0xc69a63);
for(let i=0;i<count;i++){const t=Math.random()*Math.PI*2,layer=.82+Math.random()*.22,x=16*Math.sin(t)**3,y=13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t),z=(Math.random()-.5)*2.1*(1-Math.min(1,Math.abs(y)/17)),ix=i*3;targets[ix]=x*.18*layer;targets[ix+1]=y*.18*layer;targets[ix+2]=z;positions[ix]=targets[ix]+(Math.random()-.5)*.08;positions[ix+1]=targets[ix+1]+(Math.random()-.5)*.08;positions[ix+2]=z;const radius=6+Math.random()*12,theta=Math.random()*Math.PI*2,phi=Math.acos(2*Math.random()-1);dispersed[ix]=radius*Math.sin(phi)*Math.cos(theta);dispersed[ix+1]=radius*Math.sin(phi)*Math.sin(theta);dispersed[ix+2]=radius*Math.cos(phi);const c=Math.random()>.68?gold:rose;particleColors[ix]=c.r;particleColors[ix+1]=c.g;particleColors[ix+2]=c.b}
const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.BufferAttribute(positions,3));geometry.setAttribute("color",new THREE.BufferAttribute(particleColors,3));
const material=new THREE.PointsMaterial({size:innerWidth<720?.045:.035,transparent:true,opacity:.72,vertexColors:true,depthWrite:false,blending:THREE.AdditiveBlending});
const heart=new THREE.Points(geometry,material);heart.scale.setScalar(.86);heart.rotation.z=0;heart.position.y=-.25;scene.add(heart);
const starCount=innerWidth<720?180:420,starPositions=new Float32Array(starCount*3);for(let i=0;i<starCount*3;i+=3){starPositions[i]=(Math.random()-.5)*32;starPositions[i+1]=(Math.random()-.5)*22;starPositions[i+2]=-3-Math.random()*16}const starGeometry=new THREE.BufferGeometry();starGeometry.setAttribute("position",new THREE.BufferAttribute(starPositions,3));const stars=new THREE.Points(starGeometry,new THREE.PointsMaterial({color:0xc69a63,size:.025,transparent:true,opacity:.35}));scene.add(stars);

let mouseX=0,mouseY=0,targetOpacity=.24,animationMode="heart",language="en";
addEventListener("pointermove",e=>{mouseX=(e.clientX/innerWidth-.5)*.36;mouseY=(e.clientY/innerHeight-.5)*.25});
function render(){requestAnimationFrame(render);if(!reducedMotion){heart.rotation.y+=(mouseX-heart.rotation.y)*.025;heart.rotation.x+=(-mouseY-heart.rotation.x)*.025;heart.rotation.z=Math.sin(performance.now()*.00025)*.025;stars.rotation.y+=.00008}material.opacity+=(targetOpacity-material.opacity)*.04;if(animationMode==="transition")geometry.attributes.position.needsUpdate=true;renderer.render(scene,camera)}render();

function showScreen(id,direction=1){const current=document.querySelector(".screen.active"),next=document.querySelector(`#${id}`);if(current===next)return;gsap.timeline().to(current,{autoAlpha:0,y:-18*direction,duration:reducedMotion?.01:.55,ease:"power2.in",onComplete:()=>current.classList.remove("active")}).set(next,{y:24*direction,autoAlpha:0,onComplete:()=>next.classList.add("active")}).to(next,{autoAlpha:1,y:0,duration:reducedMotion?.01:.75,ease:"power3.out"})}
async function hashValue(value){const bytes=new TextEncoder().encode(value),digest=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("")}
const inputs=[...document.querySelectorAll("#pin-inputs input")];inputs.forEach((input,index)=>{input.addEventListener("input",()=>{input.value=input.value.replace(/\D/g,"").slice(-1);if(input.value&&inputs[index+1])inputs[index+1].focus()});input.addEventListener("keydown",e=>{if(e.key==="Backspace"&&!input.value&&inputs[index-1])inputs[index-1].focus()});input.addEventListener("paste",e=>{const digits=e.clipboardData.getData("text").replace(/\D/g,"").slice(0,4);if(digits.length===4){e.preventDefault();digits.split("").forEach((d,i)=>inputs[i].value=d);inputs[3].focus()}})});
document.querySelector("#passcode-form").addEventListener("submit",async e=>{e.preventDefault();const value=inputs.map(input=>input.value).join(""),message=document.querySelector("#form-message");if(value.length!==4||await hashValue(value)!==CONFIG.passcodeHash){message.textContent=copy[language].wrong;gsap.fromTo("#pin-inputs",{x:-6},{x:6,repeat:5,yoyo:true,duration:.06,clearProps:"x"});return}document.querySelector("#pin-inputs").classList.add("success");message.textContent="";targetOpacity=.8;gsap.timeline({onComplete:()=>showScreen("hero-screen")}).to(".lock-panel",{boxShadow:"0 0 90px rgba(198,154,99,.35)",duration:.5}).to(".lock-panel",{scale:1.035,filter:"blur(8px)",autoAlpha:0,duration:reducedMotion?.01:.8,ease:"power3.in"})});
document.querySelector("#enter-button").addEventListener("click",()=>{targetOpacity=.44;gsap.to(heart.scale,{x:.72,y:.72,z:.72,duration:.8});showScreen("select-screen")});
document.querySelector("#heart-choice").addEventListener("click",()=>{targetOpacity=.96;gsap.to(heart.scale,{x:1.05,y:1.05,z:1.05,duration:1.2,ease:"power3.out"});showScreen("release-screen")});
document.querySelector("#release-button").addEventListener("click",()=>{animationMode="transition";const a=geometry.attributes.position.array,p={value:0};showScreen("memories-screen");gsap.to(p,{value:1,duration:reducedMotion?.01:2.4,ease:"power3.inOut",onUpdate:()=>{for(let i=0;i<count*3;i++)a[i]=THREE.MathUtils.lerp(targets[i],dispersed[i],p.value);geometry.attributes.position.needsUpdate=true},onComplete:()=>{animationMode="cloud";targetOpacity=.32}});gsap.fromTo(".memory-card",{autoAlpha:0,scale:.4},{autoAlpha:1,scale:1,stagger:.14,delay:reducedMotion?0:1.1,duration:reducedMotion?.01:.9,ease:"back.out(1.6)"})});
const dialog=document.querySelector("#memory-dialog");document.querySelectorAll(".memory-card").forEach(card=>card.addEventListener("click",()=>{const art=[...card.querySelector(".memory-art").classList].find(c=>c.startsWith("memory-art-")&&c!=="memory-art");document.querySelector("#dialog-art").className=`dialog-art ${art}`;document.querySelector("#dialog-title").textContent=card.dataset.title;document.querySelector("#dialog-date").textContent=card.dataset.date;dialog.showModal()}));document.querySelector("#dialog-close").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});
document.querySelector("#finale-button").addEventListener("click",()=>{const a=geometry.attributes.position.array,p={value:0};animationMode="transition";targetOpacity=.9;showScreen("finale-screen");gsap.to(p,{value:1,duration:reducedMotion?.01:2.1,ease:"power3.inOut",onUpdate:()=>{for(let i=0;i<count*3;i++)a[i]=THREE.MathUtils.lerp(dispersed[i],targets[i],p.value);geometry.attributes.position.needsUpdate=true},onComplete:()=>animationMode="heart"})});
document.querySelector("#replay-button").addEventListener("click",()=>location.reload());
document.querySelectorAll(".language").forEach(button=>button.addEventListener("click",()=>{language=button.dataset.lang;document.documentElement.lang=language==="zh"?"zh-CN":language;document.querySelectorAll(".language").forEach(item=>item.classList.toggle("active",item===button));document.querySelectorAll("[data-copy]").forEach(el=>{const key=el.dataset.copy;if(copy[language][key])el.textContent=copy[language][key]})}));
const sound=document.querySelector("#sound-toggle");sound.addEventListener("click",()=>{const active=sound.getAttribute("aria-pressed")!=="true";sound.setAttribute("aria-pressed",String(active));sound.textContent=active?"♫":"♪"});
addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.setSize(innerWidth,innerHeight)});
addEventListener("load",()=>{setTimeout(()=>document.querySelector("#loading-screen").classList.add("hidden"),500);setTimeout(()=>inputs[0].focus(),900)});
